RailGallery/Controllers/AlbumsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RailGallery.Data;
using RailGallery.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;

namespace RailGallery.Controllers
{
    /// <summary>
    /// <c>Albums Controller</c>
    /// Contains methods that allow to create, display, update and delete user albums.
    /// 
    /// Author: Maksym Hanushchak
    /// </summary>
    public class AlbumsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        /// <summary>
        /// Constructor.
        /// </summary>
        /// <param name="context">Reference to the Context object.</param>
        /// <param name="userManager">Reference to the User Manager object.</param>
        public AlbumsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        /// <summary>
        /// HTTP GET method to retrieve a list of albums that belong to the user and pass it to the view. 
        /// 
        /// GET: [host]/Author/{username}/Albums
        /// </summary>
        /// <param name="username">The user's username.</param>
        /// <param name="page">Current page.</param>
        /// <returns></returns>
        [Route("Author/{username}/Albums")]
        public async Task<IActionResult> Index(string username, int? page)
        {
            if (username == null)
            {
                return NotFound();
            }

            // Retrieve the user
            ApplicationUser user = await _userManager.FindByNameAsync(username);

            if (user == null)
            {
                return NotFound();
            }

            // Store username in a viewbag to preserve the values between different pages
            ViewBag.UserName = user.UserName;

            // Retrieve the albums that belong to the user
            List<Album> albums = await _context.Albums.Where(a => a.ApplicationUser == user).Include(a => a.ApplicationUser).Include(a => a.Images.OrderByDescending(i => i.ImageID)).ToListAsync();

            // Size of the list on one page
            int pageSize = 100;

            // Ternary operator to calculate the page number
            int pageNumber = (int)((!page.HasValue || page == 0) ? 1 : page);

            return View(albums.ToPagedList(pageNumber, pageSize)); // Redirect to the view Author/Albums
        }

        /// <summary>
        /// HTTP POST method that redirects to the create album view.
        /// 
        /// GET: [host]/Albums/Create
        /// </summary>
        /// <returns></returns>
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// HTTP POST method that creates a new album and saves it in the database based on the received form submission values.
        /// 
        /// POST: [host]/Albums/Create{FormCollection}
        /// </summary>
        /// <param name="album">Album object with the values specified in the form.</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("AlbumID,AlbumTitle,AlbumPrivacy")] Album album)
        {
            if (ModelState.IsValid)
            {
                // Retrieve the current user and add it as the album's author
                album.ApplicationUser = await _userManager.GetUserAsync(HttpContext.User);

                // Save the album in the database
                _context.Add(album);
                await _context.SaveChangesAsync();

                // Redirect back to the Upload view
                return RedirectToAction("Index", "Upload");
            }
            return View(album);
        }

        /// <summary>
        /// HTTP GET method that redirects to the album edit view.
        /// 
        /// GET: [host]/Albums/Edit/{parameters}
        /// </summary>
        /// <param name="id">The id of the album to edit.</param>
        /// <returns></returns>
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // Retrieve the currently authenticated user
            ApplicationUser currentUser = await _userManager.GetUserAsync(HttpContext.User);

            if (currentUser == null)
            {
                return NotFound();
            }

            // Retrieve the roles of the currently authenticated user and save them to a list
            IList<string> currentUserRoles = await _userManager.GetRolesAsync(currentUser);

            // Retrieve the album to edit
            Album album = await _context.Albums.Include(a => a.Images.OrderByDescending(i => i.ImageID)).Include(a => a.ApplicationUser).FirstAsync(a => a.AlbumID == id);

            // In case retrieval fails - display NotFound error
            if (album == null || currentUser == null || (album.ApplicationUser.UserName != currentUser.UserName && !currentUserRoles.Contains(Enums.Roles.Moderator.ToString())))
            {
                return NotFound();
            }

            // Store images that belong to the current user in the View Bag to display in the image select list on the edit page.
            ViewBag.Images = await _context.Images.Where(i => i.ApplicationUser.UserName == album.ApplicationUser.UserName).OrderByDescending(i => i.ImageID).Select(i =>
                                  new SelectListItem
                                  {
                                      Value = i.ImageID.ToString(),
                                      Text = (i.ImageStatus == Enums.Status.Published ? i.ImageTitle : i.ImageTitle + " (photo pending)"),
                                      Selected = _context.Images.Include(a => a.Albums).Where(a => a.ImageID == i.ImageID && a.Albums.Where(a => a.AlbumID == album.AlbumID).Any()).Any() ? true : false
                                  }).AsNoTracking().ToListAsync();

            return View(album);
        }

        /// <summary>
        /// HTTP POST method that is called after the Edit album form is submitted. Updates the album with the values specified in the form.
        /// 
        /// POST: [host]/Albums/Edit{FormCollection}
        /// </summary>
        /// <param name="id">The id of the album to edit.</param>
        /// <param name="album">The updated album object.</param>
        /// <param name="AlbumImages">The updated list of images that are in the album.</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("AlbumID,AlbumTitle,AlbumPrivacy")] Album album, string[]? AlbumImages)
        {
            if (id != album.AlbumID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                // Retrieve the user profile of the author of the album
                string username = (await _context.Albums.Include(a => a.ApplicationUser).AsNoTracking().FirstAsync(a => a.AlbumID == id)).ApplicationUser.UserName;

                // Retrieve the album that will be updated
                Album albumToUpdate = await _context.Albums.Include(a => a.Images).FirstAsync(a => a.AlbumID == id);

                // Update the values in the retrieved album object with the new values
                albumToUpdate.AlbumTitle = album.AlbumTitle;
                albumToUpdate.AlbumPrivacy = album.AlbumPrivacy;

                // Retrieve all images that belong to the current user
                List<Image> images = await _context.Images.Include(i => i.ApplicationUser).Where(i => i.ApplicationUser.UserName == username).ToListAsync();

                // Loop through all of the images and remove them from the album
                foreach (Image image in images)
                {
                    albumToUpdate.Images.Remove(image);
                }

                // Loop through the new list of images and add them to the album
                foreach (string albumImage in AlbumImages)
                {
                    albumToUpdate.Images.Add(await _context.Images.FirstAsync(a => a.ImageID.ToString() == albumImage));
                }

                // Attempt to update and save the album in the database, display an error message on fail
                try
                {
                    _context.Update(albumToUpdate);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AlbumExists(album.AlbumID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                // Redirect back to the user profile view
                return RedirectToAction("Index", "Author", new { @username = username });
            }
            return View(album);
        }

        /// <summary>
        /// HTTP GET method that retrieves information about the album to be deleted and passes it to the view.
        /// 
        /// GET: [host]/Albums/Delete{parameters}
        /// </summary>
        /// <param name="id">The id of the album to be deleted.</param>
        /// <returns></returns>
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

RailGallery/Controllers/SearchController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using RailGallery.Data;
using RailGallery.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;

#nullable enable

namespace RailGallery.Controllers
{
    /// <summary>
    /// <c>Search Controller</c>
    /// Contains methods that allow to filter and search photos and return the list in the view.
    /// 
    /// Author: Maksym Hanushchak
    /// </summary>
    public class SearchController : Controller
    {
        private readonly ILogger<SearchController> _logger;
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        /// <summary>
        /// Class constructor.
        /// </summary>
        /// <param name="logger">Reference to the Logger object</param>
        /// <param name="context">Reference to the current Context</param>
        /// <param name="userManager">Reference to the User Manager object</param>
        public SearchController(ILogger<SearchController> logger, ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _logger = logger;
            _context = context;
            _userManager = userManager;
        }


        /// <summary>
        /// HTTP GET method that displays the Search view with the form upon calling.
        /// 
        /// GET: [host]/Search
        /// </summary>
        /// <returns>Redirects to the Search form view.</returns>
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// HTTP GET method that retrieves the photos upon a search request and displays them on the Search Results view page.
        /// 
        /// GET: [host]/Search/Results/{search parameters}
        /// </summary>
        /// <param name="page">The page number of page to display.</param>
        /// <param name="ImageTitle">The image title to search.</param>
        /// <param name="ImageAuthor">The image title to search</param>
        /// <param name="ImageDescription">The image description to search.</param>
        /// <param name="LocomotiveModel">The image locomotive to search.</param>
        /// <param name="LocomotiveBuilt">The image locomotive built date to search.</param>
        /// <param name="ImageAlbum">The album name where to search images.</param>
        /// <param name="ImageCategory">The image category to search.</param>
        /// <param name="ImageTakenDate">The image date taken to search.</param>
        /// <param name="ImageLocation">The image location to search.</param>
        /// <returns></returns>
        public async Task<IActionResult> Results(int? page,
                                    string? ImageTitle,
                                    string? ImageAuthor,
                                    string? ImageDescription,
                                    string? LocomotiveModel,
                                    string? LocomotiveBuilt,
                                    string? ImageAlbum,
                                    string? ImageCategory,
                                    string? ImageTakenDate,
                                    string? ImageLocation)
        {

            // Retrieve the currently authenticated user
            ApplicationUser? currentUser = await _userManager.GetUserAsync(HttpContext.User);

            // Delare a list that will store the current user's roles
            IList<string> currentUserRoles = null;

            if (currentUser != null)
            {
                // Retireve the roles of the current user
                currentUserRoles = await _userManager.GetRolesAsync(currentUser);
            }

            // Boolean to indicate if the user is logged in at the moment
            bool userLoggedIn = currentUser != null;

            // Boolean to indicate if the user has the moderator role
            bool userIsModerator = userLoggedIn && currentUserRoles.Contains(Enums.Roles.Moderator.ToString());

            // Retrieve a list of images to search among
            IQueryable<Image>? model = _context.Images
            .Where(i => !((i.ImageStatus == Enums.Status.Pending) || (i.ImageStatus == Enums.Status.Rejected) || (i.ImagePrivacy == Enums.Privacy.Private && !(userLoggedIn && i.ApplicationUser.UserName.Equals(currentUser.UserName)))))
            .OrderByDescending(i => i.ImageUploadedDate)
            .Include(c => c.Comments)
            .Include(c => c.Likes)
            .Include(c => c.ApplicationUser)
            .Include(c => c.Category)
            .Include(c => c.Location)
            .Include(c => c.Locomotive)
            .Include(c => c.Albums)
            .AsNoTracking();

            // If the Image Title search string is received, filter the image list using this parameter
            if (!string.IsNullOrEmpty(ImageTitle))
            {
                // Filter the list of images using the receinved parameter
                model = model.Where(i => i.ImageTitle.Contains(ImageTitle));
                // Store the search parameter in the view bag to persist in the input field of the search form
                ViewBag.ImageTitle = ImageTitle;
            }

            // For the remaining IF statements below, please refer to the above description of the similar code ^

            if (!string.IsNullOrEmpty(ImageAuthor))
            {
                model = model.Where(i => i.ApplicationUser.UserName.Contains(ImageAuthor));
                ViewBag.ImageAuthor = ImageAuthor;
            }
            if (!string.IsNullOrEmpty(ImageDescription))
            {
                model = model.Where(i => i.ImageDescription.Contains(ImageDescription));
                ViewBag.ImageDescription = ImageDescription;
            }
            if (!string.IsNullOrEmpty(LocomotiveModel))
            {
                model = model.Where(i => i.Locomotive.LocomotiveModel.Contains(LocomotiveModel));
                ViewBag.LocomotiveModel = LocomotiveModel;
            }
            if (!string.IsNullOrEmpty(LocomotiveBuilt))
            {
                model = model.Where(i => i.Locomotive.LocomotiveBuilt.ToString().Contains(LocomotiveBuilt));
                ViewBag.LocomotiveBuilt = LocomotiveBuilt;
            }
            if (!string.IsNullOrEmpty(ImageAlbum))
            {
                model = model.Where(i => i.Albums.Where(a => a.AlbumTitle.Contains(ImageAlbum)).Any());
                ViewBag.ImageAlbum = ImageAlbum;
            }
            if (!string.IsNullOrEmpty(ImageCategory))
            {
                model = model.Where(i => i.Category.CategoryTitle.Contains(ImageCategory));
                ViewBag.ImageCategory = ImageCategory;
            }
            if (!string.IsNullOrEmpty(ImageTakenDate))
            {
                model = model.Where(i => i.ImageTakenDate.ToString().Contains(ImageTakenDate));
                ViewBag.ImageTakenDate = ImageTakenDate;
            }
            if (!string.IsNullOrEmpty(ImageLocation))
            {
                model = model.Where(i => i.Location.LocationName.Contains(ImageLocation));
                ViewBag.ImageLocation = ImageLocation;
            }

            // Set the maximum number of photos to display on a single page
            int pageSize = 15;

            // Calculate the current page number
            int pageNumber = (int)((!page.HasValue || page == 0) ? 1 : page);

            // Redirect to the Search Results View
            return View(model.ToPagedList(pageNumber, pageSize));
        }
    }
}

RailGallery/Views/Albums/Create.cshtml
@model RailGallery.Models.Album
@using RailGallery.Enums;

@{
    ViewData["Title"] = "Add Album";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-4 offset-md-4">
        <form asp-action="Create">
            <h4>@ViewData["Title"]</h4>
            <hr />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="AlbumTitle" class="control-label"></label>
                <input asp-for="AlbumTitle" class="form-control" />
                <span asp-validation-for="AlbumTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AlbumPrivacy" class="control-label"></label>
                <select asp-for="AlbumPrivacy" class="form-control" asp-items="Html.GetEnumSelectList<Privacy>()"></select>
                <span asp-validation-for="AlbumPrivacy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="row justify-content-between">
                    <div class="col-auto">
                        <input type="submit" value="Create Album" class="btn btn-primary" />
                    </div>
                    <div class="col-auto">
                        <a asp-controller="Albums" asp-action="Index" asp-route-username="@User.Identity.Name">Show my albums</a> | <a href="javascript:void(0);" onclick="history.go(-1);">Go back</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RailGallery/Views/Albums/Delete.cshtml
@model RailGallery.Models.Album
@using RailGallery.Enums;

@{
    ViewData["Title"] = "Delete Album";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-4 offset-md-4">
        <h4>Are you sure you want to delete this album?</h4>
        <hr />

        <div class="form-group text-center">
            @if (Model.Images.Where(i => i.ImagePrivacy != RailGallery.Enums.Privacy.Private && i.ImageStatus == Status.Published).Any()) // If the album contains a published public photo(s), display the most recent one as the album thumbnail
            {
                <img style="object-fit: cover; max-width: 300px; max-height: 200px; " src="/api/Photo/@Model.Images.Where(i=>i.ImagePrivacy != RailGallery.Enums.Privacy.Private && i.ImageStatus == Status.Published).ElementAt(0).ImagePath/Thumbnail" asp-append-version="true" alt="">
            }
            else // If the album does not contain any published public photos, display the message
            {
                <div class="text-center pt-5" style="object-fit: cover; width: 300px; height: 200px; min-width: contain; background: repeating-linear-gradient( 45deg, transparent, transparent 10px, #ccc 10px, #ccc 20px ), linear-gradient( to bottom, #eee, #999 );"><h6>This album is empty or only contains private photos.</h6></div>
            }
        </div>

        <div class="row justify-content-between">
            <div class="col-auto font-weight-bold">
                @Html.DisplayNameFor(model => model.AlbumTitle)
            </div>
            <div class="col-auto">
                @Html.DisplayFor(model => model.AlbumTitle)
            </div>
        </div>

        <div class="row justify-content-between">
            <div class="col-auto font-weight-bold">
                @Html.DisplayNameFor(model => model.AlbumPrivacy)
            </div>
            <div class="col-auto">
                @Html.DisplayFor(model => model.AlbumPrivacy)
            </div>
        </div>

        <div class="row justify-content-between">
            <div class="col-auto font-weight-bold">
                Album Owner
            </div>
            <div class="col-auto">
                <a asp-controller="Author" asp-action="Index" asp-route-username="@Model.ApplicationUser.UserName">@Html.DisplayFor(model => model.ApplicationUser.UserName)</a>
            </div>
        </div>

        <br />
        <div class="form-group">
            <div class="row justify-content-between">
                <div class="col-auto">
                    <form asp-action="Delete">
                        <input type="hidden" asp-for="AlbumID" />
                        <input type="submit" value="Delete album" class="btn btn-danger" />
                    </form>
                </div>
                <div class="col-auto">
                    <a href="javascript:void(0);" onclick="history.go(-1);">Go back</a>
                </div>
            </div>
        </div>
    </div>
</div>

RailGallery/Views/Albums/Edit.cshtml
@model RailGallery.Models.Album
@using RailGallery.Enums;
@{
    ViewData["Title"] = "Edit Album";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="row">
    <div class="col-md-4 offset-md-4">
        <form asp-action="Edit">
            <h4>@ViewData["Title"]</h4>
            <hr />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="AlbumID" />
            <div class="form-group text-center">
                @if (Model.Images.Where(i => i.ImagePrivacy != RailGallery.Enums.Privacy.Private && i.ImageStatus == Status.Published).Any()) // If the album contains a published public photo(s), display the most recent one as the album thumbnail
                {
                    <img style="object-fit: cover; max-width: 300px; max-height: 200px; " src="/api/Photo/@Model.Images.Where(i=>i.ImagePrivacy != RailGallery.Enums.Privacy.Private && i.ImageStatus == Status.Published).ElementAt(0).ImagePath/Thumbnail" asp-append-version="true" alt="">
                }
                else // If the album does not contain any published public photos, display the message
                {
                    <div class="text-center pt-5" style="object-fit: cover; width: 300px; height: 200px; min-width: contain; background: repeating-linear-gradient( 45deg, transparent, transparent 10px, #ccc 10px, #ccc 20px ), linear-gradient( to bottom, #eee, #999 );"><h6>This album is empty or only contains private photos.</h6></div>
                }
            </div>

            <div class="form-group">
                <div class="row justify-content-between">
                    <div class="col-auto">
                        <label asp-for="AlbumTitle" class="control-label"></label>
                    </div>
                    <div class="col-auto">
                        <span asp-validation-for="AlbumTitle" class="text-danger"></span>
                    </div>
                </div>
                <input asp-for="AlbumTitle" class="form-control" />
            </div>

            <div class="form-group">
                <div class="row justify-content-between">
                    <div class="col-auto">
                        <label asp-for="AlbumPrivacy" class="control-label"></label>
                    </div>
                    <div class="col-auto">
                        <span asp-validation-for="AlbumPrivacy" class="text-danger"></span>
                    </div>
                </div>
                <select asp-for="AlbumPrivacy" class="form-control" asp-items="Html.GetEnumSelectList<Privacy>()"></select>
            </div>

            <div class="form-group">
                <div class="row justify-content-between">
                    <div class="col-auto">
                        <label for="AlbumImages" class="control-label">Images</label>
                    </div>
                </div>
                <select asp-for="Images" name="AlbumImages" id="AlbumImages" class="form-control form-control-chosen" multiple size="@ViewBag.Images.Count" data-placeholder="Select Images to Add">
                    @foreach (var value in ViewBag.Images) // Display current user's images in the select list to allow to add them to the edited album
                    {
                        @if (value.Selected) // Check if the image is already in the album and if so, mark it selected
                        {
                            <option value="@value.Value" selected>@value.Text</option>
                        }
                        else
                        {
                            <option value="@value.Value">@value.Text</option>
                        }
                    }
                </select>
            </div>

            <div class="form-group">
                <div class="row justify-content-between">
                    <div class="col-auto">
                        <input type="submit" value="Apply changes" class="btn btn-primary" />
                    </div>
                    <div class="col-auto">
                        <a href="javascript:void(0);" onclick="history.go(-1);">Go Back</a>&nbsp;
                        <a asp-controller="Albums" asp-action="Delete" asp-route-id="@Model.AlbumID" class="btn btn-danger" role="button" aria-pressed="true">Delete album</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RailGallery/Views/Albums/Index.cshtml
@model IPagedList<RailGallery.Models.Album>
@using X.PagedList.Mvc.Core;
@using X.PagedList;
@using X.PagedList.Web.Common;
@using RailGallery.Enums;

<link href="/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewData["Title"] = ViewBag.UserName + "'s Albums";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="row">
    <div class="col text-center">
        <h4>@ViewData["Title"]</h4>

        @if (!(Model.Where(a => a.AlbumPrivacy == RailGallery.Enums.Privacy.Public).Any() || ((Model.Where(a => a.AlbumPrivacy == RailGallery.Enums.Privacy.Private).Any() && User.Identity.Name == ViewBag.UserName)))) // If the album contains a published public photo(s) or private photo(s) and belongs to the current user, display the most recent one as the album thumbnail
        {
            <p class="mt-5">@ViewBag.UserName does not have any public albums yet.</p>
        }
        else // If the album does not contain any published public photos, display the message
        {
            <div class="d-flex justify-content-center flex-wrap">
                @foreach (var album in Model) // Display each user's album
                {
                    string css = "";
                    bool albumPrivate = album.AlbumPrivacy.Equals(RailGallery.Enums.Privacy.Private); // set the boolean to true if the album is private
                    if (albumPrivate) // If the album is private, the background will be yellow
                    {
                        css = "alert-warning";
                    }
                    if (!albumPrivate || (albumPrivate && User.Identity.Name == album.ApplicationUser.UserName)) // If the album is public or it belongs to the current user, display it
                    {
                        <div class="d-inline-flex align-self-start p-2">
                            <a asp-controller="Search" asp-action="Results" asp-route-imagealbum="@album.AlbumTitle" asp-route-imageauthor="@album.ApplicationUser.UserName" class="text-decoration-none">
                                <div class="card btn-light @css" style="max-width: 302px;">
                                    @if (album.Images.Where(i => i.ImagePrivacy != RailGallery.Enums.Privacy.Private && i.ImageStatus == Status.Published).Any()) // If the album contains a published public photo(s) or private photo(s) and belongs to the current user, display the most recent one as the album thumbnail
                                    {
                                        <img class="card-img-top" style="object-fit: cover; max-width: 300px; max-height: 200px; min-width:contain;" src="/api/Photo/@album.Images.Where(i => i.ImagePrivacy != RailGallery.Enums.Privacy.Private && i.ImageStatus == Status.Published).ElementAt(0).ImagePath/Thumbnail" asp-append-version="true" alt="">
                                    }
                                    else // If the album does not contain any published public photos, display the message
                                    {
                                        <div class="card-img-top" style="object-fit: cover; width: 300px; height: 200px; min-width: contain; background: repeating-linear-gradient( 45deg, transparent, transparent 10px, #ccc 10px, #ccc 20px ), linear-gradient( to bottom, #eee, #999 );"><h6 class="mt-5">This album is empty or only contains private photos.</h6></div>
                                    }

                                    <div class="card-body p-2">
                                        <h6 class="card-title">@album.AlbumTitle</h6>
                                        <p class="card-text"><small><b>@album.Images.Count</b> images, @album.AlbumPrivacy.ToString()</small></p>
                                    </div>
                                </div>
                            </a>
                            @if (User.Identity.Name == album.ApplicationUser.UserName || User.IsInRole("Moderator")) // If the current user is the author of the album or a moderator, display the edit link
                            {
                                <a asp-controller="Albums" asp-action="Edit" asp-route-id="@album.AlbumID" class="position-absolute text-decoration-none shadow p-1 bg-white">Edit</a>
                            }
                        </div>
                    }
                }
            </div>
        }
    </div>
</div>