RailGallery/Controllers/AuthorController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RailGallery.Data;
using RailGallery.Models;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;

namespace RailGallery.Controllers
{
    /// <summary>
    /// <c>Author Controller</c>
    /// Contains a method that allows to retrieve public user information to display on the profile page.
    /// 
    /// Author: Maksym Hanushchak
    /// </summary>
    public class AuthorController : Controller
    {

        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        /// <summary>
        /// Constructor.
        /// </summary>
        /// <param name="context">Reference to the Context object</param>
        /// <param name="userManager">Reference to the User Manager object</param>
        public AuthorController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }


        /// <summary>
        /// HTTP GET method to retrieve public profile information based on the passed username parameter.
        /// 
        /// GET: [host]/Author/{username}
        /// </summary>
        /// <param name="username">The username of the user profile to retrieve.</param>
        /// <returns></returns>
        [Route("Author/{username}")]
        public async Task<ActionResult> Index(string? username)
        {
            if (username == null)
            {
                return NotFound();
            }

            // Find the user in the database using the User Manager
            ApplicationUser user = await _userManager.FindByNameAsync(username);

            // If the user is not found, display the not found error
            if (user == null)
            {
                return NotFound();
            }

            // Create ExpandoObject that will be used to pass recent photos and albums of the user to the view
            dynamic authorModel = new ExpandoObject();

            // Add user profile to the dynamic model
            authorModel.User = user;

            // Retrieve 10 of the user's most recent published photos and add them to the dynamic model
            authorModel.RecentPhotos = await _context.Images
                .Where(i => i.ApplicationUser.UserName.Equals(user.UserName) && i.ImageStatus == Enums.Status.Published && i.ImagePrivacy == Enums.Privacy.Public)
                .OrderByDescending(i => i.ImageUploadedDate)
                .Take(10)
                .Include(c => c.Comments)
                .Include(c => c.Likes)
                .AsNoTracking()
                .ToListAsync();

            // Retrieve 10 of the user's most recent public albums and add them to the dynamic model
            authorModel.RecentAlbums = await _context.Albums
                .Where(a => a.ApplicationUser.UserName.Equals(user.UserName))
                .OrderByDescending(a => a.AlbumID)
                .Take(10)
                .Include(a => a.Images.OrderByDescending(i => i.ImageID))
                .Include(a => a.ApplicationUser)
                .AsNoTracking()
                .ToListAsync();

            // Redirect to the Author view and pass the dynamic model with the retrieved information
            return View(authorModel);
        }
    }
}

RailGallery/Controllers/ViewController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RailGallery.Data;
using RailGallery.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RailGallery.Controllers
{
    /// <summary>
    /// <c>View Controller</c>
    /// Contains a method that allows to retrieve information and the file of the reuqested photo and pass it to the Photo View page to display.
    /// 
    /// Author: Maksym Hanushchak
    /// </summary>
    public class ViewController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        /// <summary>
        /// Class constructor.
        /// </summary>
        /// <param name="context">Reference to the current context.</param>
        /// <param name="userManager">Reference to the current User Manager object.</param>
        public ViewController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        /// <summary>
        /// HTTP GET method that retrieves information about the requested image and the file and redirects to the Photo View to display it.
        /// 
        /// GET: [host]/View{id parameter}
        /// </summary>
        /// <param name="id">ID of the photo to view.</param>
        /// <returns>Redirects to the View page of the requested photo.</returns>
        [Route("View/{id}")]
        public async Task<IActionResult> View(int? id)
        {
            // Try to retrieve the currently athenticated user
            ApplicationUser currentUser = await _userManager.GetUserAsync(HttpContext.User);

            // Retrieve a list of user roles of the current user if authenticated
            IList<string> currentUserRoles = null;
            if (currentUser != null)
            {
                currentUserRoles = await _userManager.GetRolesAsync(currentUser);
            }

            if (id == null)
            {
                return NotFound();
            }

            // Retrieve the requested image object and all corresponding objects that are related to this image
            Image image = await _context.Images
                .Include(m => m.Comments.OrderBy(c => c.CommentDate)).ThenInclude(c => c.ApplicationUser)
                .Include(m => m.Likes)
                .Include(m => m.Albums).ThenInclude(u => u.ApplicationUser)
                .Include(m => m.Favorites)
                .Include(m => m.Category)
                .Include(m => m.ApplicationUser)
                .Include(m => m.Location)
                .Include(m => m.Locomotive)
                .Include(m => m.ImageViews)
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.ImageID == id);

            // Boolean markers to indicate different conditions
            bool userLoggedIn = currentUser != null;
            bool imagePending = image.ImageStatus == Enums.Status.Pending;
            bool imageIsPrivate = image.ImagePrivacy == Enums.Privacy.Private;
            bool userIsAuthor = userLoggedIn && image.ApplicationUser.UserName.Equals(currentUser.UserName);
            bool userIsModerator = userLoggedIn && currentUserRoles.Contains(Enums.Roles.Moderator.ToString());
            bool imageRejected = image.ImageStatus == Enums.Status.Rejected;

            // Use the boolean markers above to check if the user has the permission to view the requested image
            // - Image does not exist - Display error
            // - Image is Pending and the user is not the author nor a moderator - Display error
            // - Image is Rejected and the user is not the author nor a moderator - Display error
            // - Image is Private and the user is not the author - Display error
            if ((image == null) ||
                    (imagePending && !(userIsAuthor || userIsModerator)) ||
                    (imageRejected && !(userIsAuthor || userIsModerator)) ||
                    (imageIsPrivate && !userIsAuthor))
            {
                return NotFound();
            }

            // Pass the boolean markers to the view for conditional rendering
            ViewBag.isPending = imagePending;
            ViewBag.isPrivate = imageIsPrivate;
            ViewBag.isRejected = imageRejected;
            ViewBag.isLiked = false;
            ViewBag.isFavorited = false;

            // Check if the current user has liked and/or favorited the image and pass the results as a boolean value to the view using a ViewBag
            if (currentUser != null)
            {
                // Check if the current user has liked the viewed image
                if (_context.Likes.Any(l => l.ApplicationUser.UserName == currentUser.UserName && l.Image.ImageID == image.ImageID))
                {
                    ViewBag.isLiked = true;
                }
                // Check if the current user has favorited the viewed image
                if (_context.Favorites.Any(f => f.ApplicationUser.UserName == currentUser.UserName && f.Image.ImageID == image.ImageID))
                {
                    ViewBag.isFavorited = true;
                }
            }

            // Retrieve the current date time in the EST time zone
            DateTime currentTime = TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, TimeZoneInfo.FindSystemTimeZoneById("Eastern Standard Time"));

            // Create a new Image View object
            ImageView imageView = new ImageView { DateViewed = currentTime, ImageId = image.ImageID };

            // Add the new Image View object to the dtabase - to keep track of the number of image views
            await _context.ImageViews.AddAsync(imageView);
            await _context.SaveChangesAsync();

            // Redirect to the Photo View page
            return View(image);
        }
    }
}

RailGallery/Views/Upload/Delete.cshtml
@model RailGallery.Models.Image

@{
    ViewData["Title"] = "Delete photo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-4 offset-md-4">
        <h4>Are you sure you want to remove this photo?</h4>
        <hr />

        <div class="row justify-content-center">
            <img src="/api/Photo/@Model.ImagePath/Thumbnail" asp-append-version="true" />
        </div>
        <div class="row justify-content-between">
            <div class="col-auto font-weight-bold">
                @Html.DisplayNameFor(model => model.ImageTitle)
            </div>
            <div class="col-auto">
                @Html.DisplayFor(model => model.ImageTitle)
            </div>
        </div>

        <div class="row justify-content-between">
            <div class="col-auto font-weight-bold">
                @Html.DisplayNameFor(model => model.ImageDescription)
            </div>
            <div class="col-auto">
                @Html.DisplayFor(model => model.ImageDescription)
            </div>
        </div>

        <div class="row justify-content-between">
            <div class="col-auto font-weight-bold">
                Author
            </div>
            <div class="col-auto">
                <a asp-controller="Author" asp-action="Index" asp-route-username="@Model.ApplicationUser.UserName">@Html.DisplayFor(model => model.ApplicationUser.UserName)</a>
            </div>
        </div>
        <br />
        <div class="form-group">
            <div class="row justify-content-between">
                <div class="col-auto">
                    <form asp-action="Delete">
                        <input type="hidden" asp-for="ImageID" />
                        <input type="submit" value="Delete Photo" class="btn btn-danger" />
                    </form>
                </div>
                <div class="col-auto">
                    <a asp-controller="View" asp-action="View" asp-route-id="@Model.ImageID">Open Photo</a> | <a href="javascript:void(0);" onclick="history.go(-1);">Go Back</a>
                </div>
            </div>
        </div>
    </div>
</div>

RailGallery/Views/Upload/Edit.cshtml
@model RailGallery.Models.Image
@using RailGallery.Enums;

@{
    ViewData["Title"] = "Edit Photo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-md-4 offset-md-4">
        <form asp-action="Edit">
            <h4>@ViewData["Title"]</h4>
            <hr />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ImageID" />

            <a asp-controller="View" asp-action="View" asp-route-id="@Model.ImageID">
                <img src="/api/Photo/@Model.ImagePath" asp-append-version="true" class="img-fluid shadow-sm p-1 bg-white mb-3" />
            </a>
            <div class="form-group">
                <div class="row justify-content-between">
                    <div class="col-auto">
                        <label asp-for="ImageTitle" class="control-label"></label>
                    </div>
                    <div class="col-auto">
                        <span asp-validation-for="ImageTitle" class="text-danger"></span>
                    </div>
                </div>
                <input asp-for="ImageTitle" class="form-control" />
            </div>

            <div class="form-group">
                <div class="row justify-content-between">
                    <div class="col-auto">
                        <label asp-for="ImageDescription" class="control-label"></label>
                    </div>
                    <div class="col-auto">
                        <span asp-validation-for="ImageDescription" class="text-danger"></span>
                    </div>
                </div>
                <textarea asp-for="ImageDescription" class="form-control"></textarea>
            </div>

            <div class="form-group">
                <div class="row justify-content-between">
                    <div class="col-auto">
                        <label asp-for="ImagePrivacy" class="control-label"></label>
                    </div>
                    <div class="col-auto">
                        <span asp-validation-for="ImagePrivacy" class="text-danger"></span>
                    </div>
                </div>
                <select asp-for="ImagePrivacy" class="form-control" asp-items="Html.GetEnumSelectList<Privacy>()"></select>
            </div>

            <div class="form-group">
                <div class="row justify-content-between">
                    <div class="col-auto">
                        <label asp-for="ImageStatus" class="control-label"></label>
                    </div>
                    <div class="col-auto">
                        <span asp-validation-for="ImageStatus" class="text-danger"></span>
                    </div>
                </div>
                <select asp-for="ImageStatus" class="form-control" asp-items="Html.GetEnumSelectList<Status>()"></select>
            </div>


            <div class="form-group">
                <div class="row justify-content-between">
                    <div class="col-auto">
                        <input type="submit" value="Edit Photo" class="btn btn-primary" />
                    </div>
                    <div class="col-auto">
                        <a asp-controller="View" asp-action="View" asp-route-id="@Model.ImageID">Open Photo</a> | <a href="javascript:void(0);" onclick="history.go(-1);">Go Back</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RailGallery/Views/Upload/History.cshtml
@model IEnumerable<RailGallery.Models.Image>

@{
    ViewData["Title"] = "Your Upload History";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="text-center">
    <h4>@ViewData["Title"]</h4>
    <a asp-action="Index">Upload New Photo</a>
</div>

<table class="table mt-2">
    <thead>
        <tr>
            <th class="text-center">
                Thumbnail
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImageTitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImageDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImageTakenDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImageUploadedDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImagePrivacy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImageStatus)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) // Iterate through the collection of uploaded photos to display them
        {
            string color;
            if (item.ImageStatus == RailGallery.Enums.Status.Pending) { color = "bg-warning"; } // If the status of photo is pending, set the background color to yellow
            else if (item.ImageStatus == RailGallery.Enums.Status.Rejected) { color = "bg-danger"; } // If the status of photo is rejected, set the background color to red
            else { color = "bg-success"; } // If the status of photo is published, set the background color to green
            <tr class="@color text-white">
                <td class="text-center">
                    <a asp-controller="View" asp-action="View" asp-route-id="@item.ImageID"><img src="/api/Photo/@item.ImagePath/Thumbnail" height="100" class="shadow-lg" asp-append-version="true" /></a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ImageTitle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ImageDescription)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ImageTakenDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ImageUploadedDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ImagePrivacy)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ImageStatus)
                </td>
            </tr>
        }
    </tbody>
</table>

RailGallery/Views/Upload/Index.cshtml
@model RailGallery.Models.Image
@using RailGallery.Enums;

@{
    ViewData["Title"] = "Upload Photo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-4 offset-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <h4>@ViewData["Title"]</h4>
            <hr />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <div class="row justify-content-between">
                    <div class="col-auto">
                        <label asp-for="ImageTitle" class="control-label"></label>
                    </div>
                    <div class="col-auto">
                        <span asp-validation-for="ImageTitle" class="text-danger"></span>
                    </div>
                </div>
                <input asp-for="ImageTitle" class="form-control" />
            </div>
            <div class="form-group">
                <div class="row justify-content-between">
                    <div class="col-auto">
                        <label asp-for="ImageDescription" class="control-label"></label>
                    </div>
                    <div class="col-auto">
                        <span asp-validation-for="ImageDescription" class="text-danger"></span>
                    </div>
                </div>
                <textarea asp-for="ImageDescription" class="form-control"></textarea>
            </div>
            <div class="form-group">
                <div class="row justify-content-between">
                    <div class="col-auto">
                        <label asp-for="Albums" class="control-label"></label> <small class="text-secondary">(hold CTRL to select multiple)</small>
                    </div>
                    <div class="col-auto">
                        <a asp-controller="Albums" asp-action="Create">Add New Album</a>
                        <span asp-validation-for="Albums" class="text-danger"></span>
                    </div>
                </div>
                <select asp-for="Albums" name="ImageAlbums" id="ImageAlbums" class="form-control form-control-chosen" asp-items="@ViewBag.Albums" multiple data-placeholder="Select album(s) to add the photo to">
                </select>
            </div>
            <div class="form-group">
                <div class="row justify-content-between">
                    <div class="col-auto">
                        <label asp-for="ImageCategoryID" class="control-label"></label>
                    </div>
                    <div class="col-auto">
                        <span asp-validation-for="ImageCategoryID" class="text-danger"></span>
                    </div>
                </div>
                <select asp-for="ImageCategoryID" class="form-control" asp-items="@ViewBag.Categories">
                    <option value="">Select Category</option>
                </select>
            </div>
            <div class="form-group">
                <div class="row justify-content-between">
                    <div class="col-auto">
                        <label asp-for="ImageLocomotiveID" class="control-label"></label>
                    </div>
                    <div class="col-auto">
                        <a asp-controller="Locomotive" asp-action="Create">Add New Locomotive</a>
                        <span asp-validation-for="ImageLocomotiveID" class="text-danger"></span>
                    </div>
                </div>
                <select asp-for="ImageLocomotiveID" class="form-control form-control-chosen" asp-items="@ViewBag.Locomotives" data-placeholder="Select Locomotive">
                    <option value="" selected></option>
                </select>
            </div>
            <div class="form-group">
                <div class="row justify-content-between">
                    <div class="col-auto">
                        <label asp-for="ImageLocationID" class="control-label"></label>
                    </div>
                    <div class="col-auto">
                        <a asp-controller="Location" asp-action="Create">Add New Location</a>
                        <span asp-validation-for="ImageLocationID" class="text-danger"></span>
                    </div>
                </div>
                <select asp-for="ImageLocationID" class="form-control form-control-chosen" asp-items="@ViewBag.Locations" data-placeholder="Select Location">
                    <option value="" selected></option>
                </select>
            </div>
            <div class="form-group">
                <div class="row justify-content-between">
                    <div class="col-auto">
                        <label asp-for="ImageTakenDate" class="control-label"></label>
                    </div>
                    <div class="col-auto">
                        <span asp-validation-for="ImageTakenDate" class="text-danger"></span>
                    </div>
                </div>
                <input asp-for="ImageTakenDate" class="form-control" />
            </div>
            <div class="form-group">
                <div class="row justify-content-between">
                    <div class="col-auto">
                        <label asp-for="ImagePrivacy" class="control-label"></label>
                    </div>
                    <div class="col-auto">
                        <span asp-validation-for="ImagePrivacy" class="text-danger"></span>
                    </div>
                </div>
                <select asp-for="ImagePrivacy" class="form-control" asp-items="Html.GetEnumSelectList<Privacy>()"></select>
            </div>
            <div class="form-group">
                <label asp-for="ImageFile" class="control-label"></label>
                <input asp-for="ImageFile" type="file" accept=".jpg" />
                <span asp-validation-for="ImageFile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="row justify-content-between">
                    <div class="col-auto">
                        <input type="submit" value="Upload Photo" class="btn btn-primary" />
                    </div>
                    <div class="col-auto">
                        <a asp-action="History">Upload History</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}