RailGallery/Models/Comment.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RailGallery.Models
{
    /// <summary>
    /// Model that defines a Comment.  
    /// Properties:
    /// 
    ///     - CommentID - the ID of the comment instance
    ///     - CommentText - the text body of the comment
    ///     - CommentDate - the date when the comment was created
    ///     - ApplicationUser - the author of the comment
    ///     - Image - the image to which the comment belongs
    ///     
    ///     - CommentImageID - (not mapped to a table field). The ID of the photo to which the comment belongs
    /// 
    /// Author: Maksym Hanushchak
    /// </summary>
    public class Comment
    {
        public int CommentID { get; set; }
        [Required, MaxLength(5000), Display(Name = "Comment Text")]
        public string CommentText { get; set; }
        [Display(Name = "Comment Date"), DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd hh:mm tt}")]
        public DateTime? CommentDate { get; set; }
        [Display(Name = "Comment Author")]
        public ApplicationUser ApplicationUser { get; set; }
        public Image Image { get; set; }
        [Required, NotMapped]
        public string CommentImageID { get; set; }

        /// <summary>
        /// Constructor. Sets the Comment date to the date when the comment object was created.
        /// </summary>
        public Comment()
        {
            CommentDate = TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, TimeZoneInfo.FindSystemTimeZoneById("Eastern Standard Time"));
        }
    }
}

RailGallery/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using RailGallery.Data;
using RailGallery.Models;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;

namespace RailGallery.Controllers
{
    /// <summary>
    /// <c>AdminController</c>
    /// Contains methods that allow to access and manage data by Moderator users.
    /// 
    /// Author: Maksym Hanushchak
    /// </summary>
    [Authorize(Roles = "Moderator")]
    public class AdminController : Controller
    {

        private readonly ILogger<AdminController> _logger;
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="logger">Reference to the Logger object</param>
        /// <param name="context">Reference to the Context object</param>
        /// <param name="userManager">Reference to the User Manager object</param>
        /// <param name="roleManager">Reference to the Role Manager object</param>
        public AdminController(ILogger<AdminController> logger, ApplicationDbContext context, UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _logger = logger;
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        /// <summary>
        /// Index method. Passes an object with pending photos and recent comments to the Admin/Index view.
        /// 
        /// GET: [host]/Admin
        /// </summary>
        /// <returns>View (Views/Admin/Index.cshtml)</returns>
        public IActionResult Index()
        {
            // Create ExpandoObject that will be used to pass pending images and recent comments to the view
            dynamic adminModel = new ExpandoObject();

            // Retrieve 15 pending images to pass to the view
            adminModel.PendingImages = _context.Images
                .Where(i => i.ImageStatus == Enums.Status.Pending && i.ImagePrivacy != Enums.Privacy.Private)
                .OrderBy(i => i.ImageUploadedDate)
                .Take(15)
                .Include(c => c.ApplicationUser)
                .AsNoTracking();

            // Retrieve 15 most recent comments to pass to the view
            adminModel.RecentComments = _context.Comments
                .OrderByDescending(c => c.CommentDate)
                .Take(15)
                .Include(c => c.ApplicationUser)
                .Include(c => c.Image)
                .AsNoTracking();

            return View(adminModel);
        }

        /// <summary>
        /// HttpPost method that is called from the photo review form in Views/View.cshtml.
        /// Used to approve or reject a photo.
        /// 
        /// POST: [host]/Admin/ReviewPhoto{FormCollection}
        /// </summary>
        /// <param name="collection">Values submitted in the form</param>
        /// <returns>Redirects back to the View or returns error.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ReviewPhoto([Bind("decision,ImageID")] IFormCollection collection)
        {
            string imageID = collection["ImageID"];

            if (string.IsNullOrEmpty(imageID))
            {
                return Content("Error");
            }

            Image image = await _context.Images.FirstOrDefaultAsync(m => m.ImageID.ToString() == imageID);

            // If the submitted decision is to reject the photo - change the photo status to Rejected
            if (collection["decision"] == "Reject")
            {
                image.ImageStatus = Enums.Status.Rejected;
                _context.Update(image);
                await _context.SaveChangesAsync();

                return RedirectToAction("View", "View", new { @id = image.ImageID }); // Redirect back to View
            }

            // If the submitted decision is to approve the photo - change the photo status to Approved
            if (collection["decision"] == "Approve")
            {
                image.ImageStatus = Enums.Status.Published;
                _context.Update(image);
                await _context.SaveChangesAsync();

                return RedirectToAction("View", "View", new { @id = image.ImageID }); // Redirect back to View
            }

            return Content("Error");
        }

        /// <summary>
        /// Method used to to retrieve all users and pass them to the view (Views/Admin/Users.cshtml)
        /// 
        /// GET: [host]/Users{parameters}
        /// </summary>
        /// <param name="page">Current page</param>
        /// <param name="username">Username/Email filter</param>
        /// <param name="sortOrder">Sort order</param>
        /// <returns>View (Views/Admin/Users.cshtml)</returns>
        public async Task<IActionResult> Users(int? page, string username, string sortOrder)
        {
            // Store username and sortorder in a viewbag to preserve the values between different pages
            ViewBag.SearchString = username;
            ViewBag.SortOrder = sortOrder;

            // Ternary operators to store sort order in the view bag that corresponds to the received GET parameter
            ViewBag.UsernameSort = string.IsNullOrEmpty(sortOrder) ? "username_desc" : "";
            ViewBag.EmailSort = sortOrder == "Email" ? "email_desc" : "Email";
            ViewBag.RegisteredSort = sortOrder == "Registered" ? "registered_desc" : "Registered";
            ViewBag.LastActiveSort = sortOrder == "LastActive" ? "lastactive_desc" : "LastActive";
            ViewBag.NumberPhotosSort = sortOrder == "NumberPhotos" ? "numberphotos_desc" : "NumberPhotos";
            ViewBag.NumberCommentsSort = sortOrder == "NumberComments" ? "numbercomments_desc" : "NumberComments";

            // Get list of users
            List<ApplicationUser> users = await _userManager.Users.Include(u => u.Images).Include(u => u.Comments).ToListAsync();

            // Filter the list of users if the GET filter parameter is not empty
            if (!string.IsNullOrEmpty(username))
            {
                users = users.Where(u => u.UserName.Contains(username) || u.Email.Contains(username)).ToList();
            }

            // Switch to order the list based on the requested sort order
            users = sortOrder switch
            {
                "username_desc" => users.OrderByDescending(u => u.UserName).ToList(),
                "Email" => users.OrderBy(u => u.Email).ToList(),
                "email_desc" => users.OrderByDescending(u => u.Email).ToList(),
                "Registered" => users.OrderBy(u => u.RegisterationDate).ToList(),
                "registered_desc" => users.OrderByDescending(u => u.RegisterationDate).ToList(),
                "LastActive" => users.OrderBy(u => u.LastActivityDate).ToList(),
                "lastactive_desc" => users.OrderByDescending(u => u.LastActivityDate).ToList(),
                "NumberPhotos" => users.OrderBy(u => u.Images.Count).ToList(),
                "numberphotos_desc" => users.OrderByDescending(u => u.Images.Count).ToList(),
                "NumberComments" => users.OrderBy(u => u.Comments.Count).ToList(),
                "numbercomments_desc" => users.OrderByDescending(u => u.Comments.Count).ToList(),
                _ => users.OrderBy(u => u.UserName).ToList(),
            };

            // Size of the list on one page
            int pageSize = 10;

            // Ternary operator to calculate the page number
            int pageNumber = (int)((!page.HasValue || page == 0) ? 1 : page);

            return View(users.ToPagedList(pageNumber, pageSize));
        }

        /// <summary>
        /// GET Method to retrieve a list of roles for the user and pass them to the view.
        /// 
        /// GET: [host]/Admin/Roles{parameters}
        /// </summary>
        /// <param name="username">Username of the user</param>
        /// <returns>View (Views/Admin/Roles.cshtml)</returns>
        public async Task<IActionResult> Roles(string username)
        {
            if (username == null)
            {
                return NotFound();
            }

            ViewBag.username = username; // Store username in the view bag to reference in the UI

            // Retrieve the user
            ApplicationUser user = await _userManager.FindByNameAsync(username);

            if (user == null)
            {
                return NotFound();
            }

            // Create a viewmodel to display the roles
            List<UserRolesViewModel> model = new List<UserRolesViewModel>();

            // Get all roles
            List<IdentityRole> roles = await _roleManager.Roles.ToListAsync();

            // Iterate through all roles and add them to a list to display in the UI <select> component
            foreach (IdentityRole role in roles)
            {
                UserRolesViewModel userRolesViewModel = new UserRolesViewModel
                {
                    RoleId = role.Id,
                    RoleName = role.Name
                };
                if (await _userManager.IsInRoleAsync(user, role.Name)) // If the user has the role, mark it as selected
                {
                    userRolesViewModel.Selected = true;
                }
                else
                {
                    userRolesViewModel.Selected = false;
                }
                model.Add(userRolesViewModel);
            }
            return View(model);
        }

        /// <summary>
        /// HTTP POST method to update the user's role.
        /// 

RailGallery/Controllers/CommentsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RailGallery.Data;
using RailGallery.Models;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace RailGallery.Controllers
{
    /// <summary>
    /// <c>Comments Controller</c>
    /// Contains a method that allows to create and delete comments and calls the corresponding views to display the comments.
    /// 
    /// Author: Maksym Hanushchak
    /// </summary>
    public class CommentsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        /// <summary>
        /// Class constructor.
        /// </summary>
        /// <param name="context">Reference to the Context object</param>
        /// <param name="userManager">Reference to the User Manager object</param>
        public CommentsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        /// <summary>
        /// HTTP POST method to create a new comment and save it in the database. This method is called upon submission of the comments form.
        /// 
        /// POST: [host]/Comments/Create{FormCollection}
        /// </summary>
        /// <param name="comment"></param>
        /// <returns></returns>
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CommentID,CommentText,CommentImageID")] Comment comment)
        {
            // Check if the submitted form data is valid
            if (ModelState.IsValid)
            {
                // Retrieve the photo to which the comment is posted and reference it in the new comment object
                comment.Image = await _context.Images.FirstOrDefaultAsync(i => i.ImageID == Convert.ToInt32(comment.CommentImageID));

                // Retrieve the currently authenticated user
                ApplicationUser currentUser = await _userManager.GetUserAsync(HttpContext.User);

                // If the user retrieval fails - display error
                if (currentUser == null)
                {
                    return Content("Error");
                }
                else // Save a reference to the comment author in the new comment object
                {
                    comment.ApplicationUser = currentUser;
                }

                // Retrieve the image to which the comment is added
                Image image = await _context.Images.FirstOrDefaultAsync(m => m.ImageID == comment.Image.ImageID);

                // Retrieve the photo to which the comment is posted and reference it in the new comment object
                if (image == null)
                {
                    return Content("Error");
                }
                else
                {
                    comment.Image = image;
                }

                // Save the new comment in the database
                _context.Add(comment);
                await _context.SaveChangesAsync();

                // Redirect back to the image view
                return RedirectToAction("View", "View", new { @id = comment.Image.ImageID });
            }
            return Content("Error");
        }


        /// <summary>
        /// HTTP GET method that displays the comment removal page with a confirmation button and comment information.
        /// 
        /// GET: [host]/Cooments/Delete{id parameter}
        /// </summary>
        /// <param name="id">The id of the comment to delete.</param>
        /// <returns></returns>
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // Retrieve the comment to be deleted and its metadata
            Comment comment = await _context.Comments
                .Include(c => c.Image)
                .Include(c => c.ApplicationUser)
                .FirstOrDefaultAsync(m => m.CommentID == id);

            if (comment == null)
            {
                return NotFound();
            }

            // Retrieve the currently authentcated user
            ApplicationUser currentUser = await _userManager.GetUserAsync(HttpContext.User);

            // Declare a list to store user roles
            IList<string> currentUserRoles = null;

            if (currentUser != null)
            {
                // Retrieve the roles of the current user
                currentUserRoles = await _userManager.GetRolesAsync(currentUser);
            }

            // If the user has the permission to remove the comment, redirect to the comment deletion view
            if (currentUser.UserName != comment.ApplicationUser.UserName && !currentUserRoles.Contains(Enums.Roles.Moderator.ToString()))
            {
                return RedirectToAction("View", "View", new { @id = comment.Image.ImageID });
            }

            return View(comment);
        }

        /// <summary>
        /// HTTP POST method that is called upon the submission of the comment deletion form.
        /// Deletes the requested comment object from the database.
        /// 
        /// POST: [host]/Cooments/Delete{id parameter}
        /// </summary>
        /// <param name="id">The id of the comment to delete.</param>
        /// <returns></returns>
        [HttpPost, ActionName("Delete")]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            // Retrieve the comment to be deleted
            Comment comment = await _context.Comments.Include(c => c.Image).FirstAsync(m => m.CommentID == id);

            // Remove the comment from the database
            _context.Comments.Remove(comment);
            await _context.SaveChangesAsync();

            // Redirect back to the photo view
            return RedirectToAction("View", "View", new { @id = comment.Image.ImageID });
        }
    }
}

RailGallery/Views/View/View.cshtml
@model RailGallery.Models.Image
@using RailGallery.Enums;

@{
    ViewData["Title"] = Model.ImageTitle;
    ViewData["ImageID"] = Model.ImageID;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">

    <div class="w-100 text-center mb-2">

        @if (ViewBag.isPending) // If the photo has pending status, display the message that it hasn't been reviewed yet
        {
            <div class="alert alert-warning" role="alert">
                This photo has not been reviewed yet.
                @if (User.IsInRole("Moderator")) // If the current user is moderator, display the review options to Approve or Reject photo
                {
                    <br />
                    <form asp-controller="Admin" asp-action="ReviewPhoto" method="post">
                        <input type="hidden" name="ImageID" value="@Model.ImageID" />
                        <button value="Approve" name="decision" type="submit" class="btn btn-success mr-2">Approve</button>
                        <button value="Reject" name="decision" type="submit" class="btn btn-danger">Decline</button>
                    </form>
                }
            </div>
        }
        else if (ViewBag.isRejected) // If the photo is rejected, display the message to inform the user
        {
            <div class="alert alert-danger" role="alert">
                This photo has been rejected.
            </div>
        }
        else if (ViewBag.isPrivate) // If the photo is private, display the message to inform the user
        {
            <div class="alert alert-warning" role="alert">
                This photo is uploaded as <b>private</b> and only visible to you.
            </div>
        }
        <img src="/api/Photo/@Model.ImagePath" asp-append-version="true" class="img-fluid shadow-sm p-1 bg-white " />
    </div>


    <div class="col-md-6 offset-md-3">
        <div class="row mt-3 mb-3">
            <div class="col">
                @if (Model.Albums.Count > 0) // If the photo belongs to any albums, display them as links
                {
                    if (Model.Albums.Count == 1) // If there is only one album the photo belongs to,
                    {
                        // If the current user has the permission to view this album, display the album name
                        if (Model.Albums.ElementAt(0).AlbumPrivacy != Privacy.Private || User.Identity.Name == Model.Albums.ElementAt(0).ApplicationUser.UserName)
                        {
                            <div>Album: <a asp-controller="Search" asp-action="Results" asp-route-imagealbum="@Model.Albums.ElementAt(0).AlbumTitle" asp-route-imageauthor="@Model.Albums.ElementAt(0).ApplicationUser.UserName">@Model.Albums.ElementAt(0).AlbumTitle</a></div>
                        }
                    }
                    else // If the photo belongs to multiple albums, display them in a list
                    {
                        <div>Albums:</div>
                        <ul>
                            @foreach (Album album in Model.Albums) // Iterate through the list of albums
                            {
                                // If the current user has the permission to view this album, display the album name in the list
                                if (album.AlbumPrivacy != Privacy.Private || User.Identity.Name == album.ApplicationUser.UserName)
                                {
                                    <li><a asp-controller="Search" asp-action="Results" asp-route-imagealbum="@album.AlbumTitle" asp-route-imageauthor="@album.ApplicationUser.UserName">@album.AlbumTitle</a></li>
                                }
                            }
                        </ul>
                    }
                }
                Category:  <a asp-controller="Search" asp-action="Results" asp-route-imagecategory="@Model.Category.CategoryTitle">@Html.DisplayFor(model => model.Category.CategoryTitle)</a>
            </div>
            <div class="col text-center">
                <h5>@Html.DisplayFor(model => model.ImageTitle)</h5>
            </div>
            <div class="col text-right">
                by <a asp-controller="Author" asp-action="Index" asp-route-username="@Model.ApplicationUser.UserName">@Html.DisplayFor(model => model.ApplicationUser.UserName)</a>
                <br />
                in <a asp-controller="Search" asp-action="Results" asp-route-imagelocation="@Model.Location.LocationName">@Html.DisplayFor(model => model.Location.LocationName)</a> on <a asp-controller="Search" asp-action="Results" asp-route-imagetakendate="@Model.ImageTakenDate.ToShortDateString()">@Html.DisplayFor(model => model.ImageTakenDate)</a>
            </div>
        </div>
        @if (Model.ImagePrivacy != Privacy.Private && Model.ImageStatus == Status.Published && User.Identity.IsAuthenticated) // If the photo is public and the user is authenticated, allow the user to add this photo to the Liked/Favorited collection
        {
            <form asp-controller="LikeFavorite" asp-action="LikeOrFavorite" method="post">
                <input type="hidden" name="ImageID" value="@Model.ImageID" />
                <div class="row mt-2 mb-2">
                    <div class="col text-center">
                        <button value="Like" name="action" type="submit" class="btn btn-link text-decoration-none">
                            @if (ViewBag.isLiked) // Conditional rendering, displays a control based on whether the current user has already liked this photo
                            {
                                <h5><i class="fas fa-heart"></i> Remove Like</h5>
                            }
                            else
                            {
                                <h5><i class="far fa-heart"></i> Like Photo</h5>
                            }
                        </button>
                    </div>
                    <div class="col text-center">
                        <button value="Favorite" name="action" type="submit" class="btn btn-link text-decoration-none">
                            @if (ViewBag.isFavorited) // Conditional rendering, displays a control based on whether the current user has already favorited this photo
                            {
                                <h5><i class="fas fa-star"></i> Remove from Favorites</h5>
                            }
                            else
                            {
                                <h5><i class="far fa-star"></i> Add to Favorites</h5>
                            }
                        </button>
                    </div>
                </div>
            </form>
        }
        <div class="row mb-3 mt-3">
            <div class="col-4 border-right">
                <h6>Details</h6>
                Total Views: @Model.ImageViews.Count
                <br />
                Locomotive: <a asp-controller="Search" asp-action="Results" asp-route-locomotivemodel="@Model.Locomotive.LocomotiveModel">@Html.DisplayFor(model => model.Locomotive.LocomotiveModel)</a>
                <br />
                Built: <a asp-controller="Search" asp-action="Results" asp-route-locomotivebuilt="@Model.Locomotive.LocomotiveBuilt.ToShortDateString()">@Html.DisplayFor(model => model.Locomotive.LocomotiveBuilt.Year)</a>
            </div>
            <div class="col-8 border-left">
                <h6>Description</h6>
                @Html.DisplayFor(model => model.ImageDescription)
            </div>
        </div>
        @if (User.IsInRole("Moderator")) // If the current user is a moderator, display links to edit and delete this photo
        {
            <div class="alert alert-warning text-center" role="alert">
                <a asp-controller="Upload" asp-action="Edit" class="btn btn-info" asp-route-id="@Model.ImageID" role="button" aria-pressed="true">Edit Photo</a>&nbsp;&nbsp;
                <a asp-controller="Upload" asp-action="Delete" class="btn btn-danger" asp-route-id="@Model.ImageID" role="button" aria-pressed="true">Delete Photo</a>
            </div>
        }

        @if (Model.ImagePrivacy != Privacy.Private && Model.ImageStatus == Status.Published) // If the photo is not private and has status published, display the comments form
        {
            <partial name="_CommentForm" model="new Comment { Image = Model }" />

            <h5>Comments <span class="text-secondary">(@Model.Comments.Count)</span></h5>
            <hr />
            @if (Model.Comments.Count > 0) // If the photo has any comments, display them
            {
                @foreach (var comment in Model.Comments) // Iterate through the collection of comments to display them
                {
                    bool authorOrModerator = false; 
                    // If the current user is the author of the comment or a moderator, set the boolean value to true
                    if (User.Identity.Name == comment.ApplicationUser.UserName || User.IsInRole("Moderator"))
                    {
                        authorOrModerator = true;
                    }

                    <div class="card border-primary mb-3">
                        <div class="card-header">
                            <div class="row justify-content-between">
                                <div class="col-auto">
                                    <a asp-controller="Author" asp-action="Index" asp-route-username="@comment.ApplicationUser.UserName"><b>@comment.ApplicationUser.UserName</b></a> @if (User.Identity.Name == comment.ApplicationUser.UserName)
                                    {<span class='text-secondary font-weight-bold'>(You)</span>} on @comment.CommentDate
                                </div>
                                @if (authorOrModerator) // If the current user is author of the comment or a moderator, display the remove link 
                                {
                                    <div class="col-auto">
                                        <a asp-controller="Comments" asp-action="Delete" asp-route-id="@comment.CommentID">Remove</a>
                                    </div>
                                }

                            </div>
                        </div>
                        <div class="card-body">
                            @comment.CommentText
                        </div>
                    </div>
                }
            }
            else // If there is no comments to display, display the message
            {
                <p>This photo does not have any comments.</p>
            }
        }
    </div>
</div>

<script src="https://kit.fontawesome.com/d3137ef294.js" crossorigin="anonymous"></script>

RailGallery/Views/View/_CommentForm.cshtml
@model RailGallery.Models.Comment
<h4>New Comment</h4>
<hr />
@if (User.Identity.IsAuthenticated)
{
    <div class="row">
        <div class="col-xl">
            <form asp-action="PostComment" method="POST">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="CommentText" class="control-label"></label>
                    <textarea asp-for="CommentText" class="form-control"></textarea>
                    <span asp-validation-for="CommentText" class="text-danger"></span>
                    <input type="hidden" asp-for="Image.ImageID" value="@Model.Image.ImageID" />
                </div>
                <div class="form-group text-right">
                    <input type="submit" value="Publish Comment" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
} else 
{
    <div><p><a asp-area="Identity" asp-page="/Account/Login">Log in</a> to post a comment.</p></div>
}


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}