RailGallery/Controllers/TopController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using RailGallery.Data;
using RailGallery.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;

namespace RailGallery.Controllers
{
    /// <summary>
    /// <c>Top Controller</c>
    /// Contains a method that allows to retrieve a list of the most viewed photos in a specified time range.
    /// 
    /// Author: Maksym Hanushchak 
    /// </summary>
    public class TopController : Controller
    {

        private readonly ILogger<TopController> _logger;
        private readonly ApplicationDbContext _context;

        /// <summary>
        /// Class constructor.
        /// </summary>
        /// <param name="logger">Reference to the current Logger object.</param>
        /// <param name="context">Reference to the current context.</param>
        public TopController(ILogger<TopController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        /// <summary>
        /// HTTP GET method that generates a list of the most viewed photos in a specified time range upon calling.
        /// </summary>
        /// <param name="time">Time range (values: 24hours, week, month).</param>
        /// <param name="page">The page number of the page to display.</param>
        /// <returns></returns>
        public async Task<IActionResult> Index(string time, int? page)
        {
            // Create a list to store the images retrieved below
            List<Image> images = null;

            // Retrieve the current date and time in the EST time zone
            DateTime currentTime = TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, TimeZoneInfo.FindSystemTimeZoneById("Eastern Standard Time"));

            // If the requested time range is 24 hours, retrieve the most viewed images in the past 24 hours from the current date
            if (string.IsNullOrEmpty(time) || time.ToLower() == "24hours")
            {
                images = await _context.Images
                .Where(i => i.ImageStatus == Enums.Status.Published && i.ImagePrivacy != Enums.Privacy.Private)
                .Include(i => i.ImageViews.Where(v => v.DateViewed >= currentTime.AddHours(-24)))
                .OrderByDescending(i => i.ImageViews.Where(v => v.DateViewed >= currentTime.AddHours(-24)).Count()).ThenByDescending(i => i.ImageUploadedDate)
                .Include(c => c.Likes)
                .Include(c => c.Comments)
                .Include(c => c.ApplicationUser)
                .AsNoTracking()
                .ToListAsync();
            }
            // If the requested time range is a week, retrieve the most viewed images in the past week from the current date
            else if (time.ToLower() == "week")
            {
                images = await _context.Images
                .Where(i => i.ImageStatus == Enums.Status.Published && i.ImagePrivacy != Enums.Privacy.Private)
                .Include(i => i.ImageViews.Where(v => v.DateViewed >= currentTime.AddHours(-168)))
                .OrderByDescending(i => i.ImageViews.Where(v => v.DateViewed >= currentTime.AddHours(-168)).Count()).ThenByDescending(i => i.ImageUploadedDate)
                .Include(c => c.Likes)
                .Include(c => c.Comments)
                .Include(c => c.ApplicationUser)
                .AsNoTracking()
                .ToListAsync();
            }
            // If the requested time range is a month, retrieve the most viewed images in the past month from the current date
            else if (time.ToLower() == "month")
            {
                images = await _context.Images
                .Where(i => i.ImageStatus == Enums.Status.Published && i.ImagePrivacy != Enums.Privacy.Private)
                .Include(i => i.ImageViews.Where(v => v.DateViewed >= currentTime.AddHours(-730)))
                .OrderByDescending(i => i.ImageViews.Where(v => v.DateViewed >= currentTime.AddHours(-730)).Count()).ThenByDescending(i => i.ImageUploadedDate)
                .Include(c => c.Likes)
                .Include(c => c.Comments)
                .Include(c => c.ApplicationUser)
                .AsNoTracking()
                .ToListAsync();
            }
            // If the parameter is not recognized, return the Not Found error
            else
            {
                return NotFound();
            }

            // Store the requested time range in a view bag to send back and display in the view
            ViewBag.Time = time;

            // Specify the number of images on a single page
            int pageSize = 15;

            // Calculate the current page number
            int pageNumber = (int)((!page.HasValue || page == 0) ? 1 : page);

            // Redirect to the view
            return View(images.ToPagedList(pageNumber, pageSize));
        }
    }
}

RailGallery/Controllers/ViewController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RailGallery.Data;
using RailGallery.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RailGallery.Controllers
{
    /// <summary>
    /// <c>View Controller</c>
    /// Contains a method that allows to retrieve information and the file of the reuqested photo and pass it to the Photo View page to display.
    /// 
    /// Author: Maksym Hanushchak
    /// </summary>
    public class ViewController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        /// <summary>
        /// Class constructor.
        /// </summary>
        /// <param name="context">Reference to the current context.</param>
        /// <param name="userManager">Reference to the current User Manager object.</param>
        public ViewController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        /// <summary>
        /// HTTP GET method that retrieves information about the requested image and the file and redirects to the Photo View to display it.
        /// 
        /// GET: [host]/View{id parameter}
        /// </summary>
        /// <param name="id">ID of the photo to view.</param>
        /// <returns>Redirects to the View page of the requested photo.</returns>
        [Route("View/{id}")]
        public async Task<IActionResult> View(int? id)
        {
            // Try to retrieve the currently athenticated user
            ApplicationUser currentUser = await _userManager.GetUserAsync(HttpContext.User);

            // Retrieve a list of user roles of the current user if authenticated
            IList<string> currentUserRoles = null;
            if (currentUser != null)
            {
                currentUserRoles = await _userManager.GetRolesAsync(currentUser);
            }

            if (id == null)
            {
                return NotFound();
            }

            // Retrieve the requested image object and all corresponding objects that are related to this image
            Image image = await _context.Images
                .Include(m => m.Comments.OrderBy(c => c.CommentDate)).ThenInclude(c => c.ApplicationUser)
                .Include(m => m.Likes)
                .Include(m => m.Albums).ThenInclude(u => u.ApplicationUser)
                .Include(m => m.Favorites)
                .Include(m => m.Category)
                .Include(m => m.ApplicationUser)
                .Include(m => m.Location)
                .Include(m => m.Locomotive)
                .Include(m => m.ImageViews)
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.ImageID == id);

            // Boolean markers to indicate different conditions
            bool userLoggedIn = currentUser != null;
            bool imagePending = image.ImageStatus == Enums.Status.Pending;
            bool imageIsPrivate = image.ImagePrivacy == Enums.Privacy.Private;
            bool userIsAuthor = userLoggedIn && image.ApplicationUser.UserName.Equals(currentUser.UserName);
            bool userIsModerator = userLoggedIn && currentUserRoles.Contains(Enums.Roles.Moderator.ToString());
            bool imageRejected = image.ImageStatus == Enums.Status.Rejected;

            // Use the boolean markers above to check if the user has the permission to view the requested image
            // - Image does not exist - Display error
            // - Image is Pending and the user is not the author nor a moderator - Display error
            // - Image is Rejected and the user is not the author nor a moderator - Display error
            // - Image is Private and the user is not the author - Display error
            if ((image == null) ||
                    (imagePending && !(userIsAuthor || userIsModerator)) ||
                    (imageRejected && !(userIsAuthor || userIsModerator)) ||
                    (imageIsPrivate && !userIsAuthor))
            {
                return NotFound();
            }

            // Pass the boolean markers to the view for conditional rendering
            ViewBag.isPending = imagePending;
            ViewBag.isPrivate = imageIsPrivate;
            ViewBag.isRejected = imageRejected;
            ViewBag.isLiked = false;
            ViewBag.isFavorited = false;

            // Check if the current user has liked and/or favorited the image and pass the results as a boolean value to the view using a ViewBag
            if (currentUser != null)
            {
                // Check if the current user has liked the viewed image
                if (_context.Likes.Any(l => l.ApplicationUser.UserName == currentUser.UserName && l.Image.ImageID == image.ImageID))
                {
                    ViewBag.isLiked = true;
                }
                // Check if the current user has favorited the viewed image
                if (_context.Favorites.Any(f => f.ApplicationUser.UserName == currentUser.UserName && f.Image.ImageID == image.ImageID))
                {
                    ViewBag.isFavorited = true;
                }
            }

            // Retrieve the current date time in the EST time zone
            DateTime currentTime = TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, TimeZoneInfo.FindSystemTimeZoneById("Eastern Standard Time"));

            // Create a new Image View object
            ImageView imageView = new ImageView { DateViewed = currentTime, ImageId = image.ImageID };

            // Add the new Image View object to the dtabase - to keep track of the number of image views
            await _context.ImageViews.AddAsync(imageView);
            await _context.SaveChangesAsync();

            // Redirect to the Photo View page
            return View(image);
        }
    }
}

RailGallery/Views/Top/Index.cshtml
@model IPagedList<RailGallery.Models.Image>
@using X.PagedList.Mvc.Core;
@using X.PagedList;
@using X.PagedList.Web.Common;
@{
    ViewData["Title"] = "Top Photos";
}


<div class="row">
    <div class="col text-center">
        <h4 class="mb-3">@ViewData["Title"]</h4>

        <div class="btn-group mb-3" role="group" aria-label="Basic example">
            <a href="?time=24hours" type="button" class="btn btn-primary">Past 24 Hours</a>
            <a href="?time=week" type="button" class="btn btn-primary">Past Week</a>
            <a href="?time=month" type="button" class="btn btn-primary">Past Month</a>
        </div>

        @if (Model.Count() == 0) // If there are no photos to display, display the message
        {
            <p class="mt-5">No photos found.</p>
        }
        else // If there are any photos to display, render the following HTML
        {
            <div class="mt-2">
                @Html.PagedListPager(Model, page => Url.Action("Index", "Top", new // Pagination
           {
               page, // Current page
               time = ViewBag.Time // The time period of the statistics
           }), new PagedListRenderOptions
           {
               ContainerDivClasses = new string[] { "pagination justify-content-center" },
               LinkToPreviousPageFormat = "Previous",
               LinkToNextPageFormat = "Next",
               LiElementClasses = new string[] { "page-item" },
               PageClasses = new string[] { "page-link" }
           })
            </div>

            <div class="d-flex justify-content-center flex-wrap">
                @foreach (var image in Model) // Iterate through the collection of photos to display them
                {

                    <div class="d-inline-flex align-self-start p-2">
                        <a asp-controller="View" asp-action="View" asp-route-id="@image.ImageID" class="text-decoration-none">
                            <div class="card btn-light" style="max-width: 302px;">
                                <img class="card-img-top" style="object-fit: cover; max-width: 300px; max-height: 200px; min-width: fit-content;" src="/api/Photo/@image.ImagePath/Thumbnail" asp-append-version="true" alt="Card image cap">
                                <div class="card-body p-2">
                                    <h6 class="card-title">@image.ImageTitle</h6>
                                    <h6 class="card-subtitle mb-1 text-muted">by <b>@image.ApplicationUser.UserName</b></h6>
                                    <p class="card-text"><small><b>@image.ImageViews.Count</b> views, <b>@image.Comments.Count</b> comments, <b>@image.Likes.Count</b> likes</small></p>
                                </div>
                            </div>
                        </a>
                    </div>
                }
            </div>
            <div class="mt-4">
                @Html.PagedListPager(Model, page => Url.Action("Index", "Top", new // Pagination
           {
               page, // Current page
               time = ViewBag.Time // The time period of the statistics
           }), new PagedListRenderOptions
           {
               ContainerDivClasses = new string[] { "pagination justify-content-center" },
               LinkToPreviousPageFormat = "Previous",
               LinkToNextPageFormat = "Next",
               LiElementClasses = new string[] { "page-item" },
               PageClasses = new string[] { "page-link" }
           })
            </div>
        }
    </div>
</div>